### ISSUE TITLE
Request for Processed Dataset Used in "FAR: Flexible, Accurate and Robust 6DoF Relative Camera Pose Estimation"

### ISSUE THREAD

**Issue by pingpingwuqiQAQ** [crockwell/far#11]
Hello,

First of all, thank you for your great work on the paper "FAR: Flexible, Accurate and Robust 6DoF Relative Camera Pose Estimation." I have been reading the paper with great interest, and I am particularly keen on replicating and further building upon your results.

However, I noticed that the original datasets (StreetLearn and InteriorNet) are quite large and contain a lot of data not directly related to the task of 6DoF relative camera pose estimation. I was wondering if you could share the pre-processed datasets used in your experiments, as this would help me focus on the core task and ensure consistency with your approach.

Thank you for considering my request, and I appreciate any assistance you can provide!

Best regards,
Wangping Wu

**Comment by crockwell** [comment]
Hi Wangping Wu,

Thanks for your interest! Unfortunately, for licensing reasons I can't directly share the InteriorNet and StreetLearn datasets. The link in the README takes you [here](https://github.com/RuojinCai/ExtremeRotation_code#dataset). This code will let you render the data we use for our experiments.

That being said, it can be time consuming and tricky to collect as you point out. Fortunately, we also do experiments on Matterport and Map-free datasets. For easy replication, I definitely recommend you try those datasets. They also have ground truth translation in addition to rotation -- StreetLearn and InteriorNet have only rotation.

Hope this helps!
Chris

**Comment by pingpingwuqiQAQ** [comment]
Dear Chris,

Thank you for your reply and helpful suggestions! I appreciate your guidance and will definitely explore the recommended datasets.

Best regards,
Wangping Wu
