### ISSUE TITLE
about prior_ransac method

### ISSUE THREAD

**Issue by wuqun-tju** [crockwell/far#5]
Sorry to bother you, I found another phenomenon running code.
 （1）In mp3d_loftr, the E result from prior_ransac is same everytime when I run [demo.sh]  multitimes with the same config
   (2)  In mapfree_6dreg, the E result from prior_ransac is different everytime when I run [demo.sh]  multitimes with the same config.
then I print some log , it shows, idxs [here](https://github.com/crockwell/far/blob/main/mapfree_6dreg/third_party/prior_ransac/ransac.py#L379) is different everytime even all inputs are same. Could you help me to figure it out

**Comment by crockwell** [comment]
Hmm that is an interesting find, thanks for point out. Must be to do with seeding. Unfortunately at the moment I don't have time to dig into this :( 

By the way, if you end up getting consistent performance, that would be super helpful if you could add a pull request! But for sure no pressure.
