### ISSUE TITLE
mp3d_loftr, demo

### ISSUE THREAD

**Issue by SongMingtao-NUDT** [crockwell/far#7]
Hello, when I run the demo in mp3d_loftr, the result I get is different from the "expected prediction" in 'demo.sh'.
The result I get is:
 [[ 0.0201 -0.1913  0.9813 -0.4618]
 [ 0.1811  0.966   0.1846 -0.1645]
 [-0.9833  0.174   0.054   0.8716]]
But the "expected prediction" in 'demo.sh' is :
[ 0.0367 -0.1899  0.9811 -0.4666]
[ 0.1938  0.9645  0.1795 -0.1628]
[-0.9803  0.1836  0.0722  0.8693]
I want to know if these errors are within allowable limits.  If not, is my result wrong or the "expected prediction" wrong?

**Comment by crockwell** [comment]
Hi Songming,

Ahh that is a bit pesky. I'd say that's within reasonable limits. If I had to guess what is going on, perhaps PyTorch or other versioning is slightly different than what I ran for this (I used PyTorch 1 Anaconda env for mp3d)? In any case, you are still closely replicating results. If you're concerned about benchmarking, you could try re-running evaluation. I bet it would be very close. Though let me know if you are concerned.

Best,
Chris

**Comment by 1751041340smt** [comment]
Yea, just as you guessed, the result of the re-running evaluation is very close to the data in the paper. 
Thank you for your reply very much.

**Comment by SongMingtao-NUDT** [comment]
> Hi Songming,
> 
> Ahh that is a bit pesky. I'd say that's within reasonable limits. If I had to guess what is going on, perhaps PyTorch or other versioning is slightly different than what I ran for this (I used PyTorch 1 Anaconda env for mp3d)? In any case, you are still closely replicating results. If you're concerned about benchmarking, you could try re-running evaluation. I bet it would be very close. Though let me know if you are concerned.
> 
> Best, Chris

Yea, just as you guessed, the result of the re-running evaluation is very close to the data in the paper.
Thank you for your reply very much.
